-- =============================================================================
-- Embedded documentation helper (extended properties).
--
-- Why it exists: `sp_addextendedproperty` FAILS if the property already exists, and
-- `sp_updateextendedproperty` fails if it does NOT exist. In a run-always script that
-- would require a 6-line IF EXISTS/ELSE per documented column (~130 columns).
-- This helper performs the upsert and keeps each call to a single line.
--
-- MS_Description documentation shows up in SSMS and Azure Data Studio, becomes
-- <summary> in the classes generated by `dotnet ef dbcontext scaffold`, and feeds the
-- generation of docs/DATA-DICTIONARY.md.
-- =============================================================================

CREATE OR ALTER PROCEDURE dbo.usp_Decco_SetDescription
    @Table    SYSNAME,
    @Column    SYSNAME        = NULL,   -- NULL = TABLE description
    -- ⚠️ Do NOT use NVARCHAR(MAX) here. The @value parameter of sp_addextendedproperty
    -- is SQL_VARIANT, and sql_variant does NOT support MAX types — passing nvarchar(max)
    -- results in "Operand type clash: nvarchar(max) is incompatible with sql_variant"
    -- (error 206). The safe practical limit for nvarchar inside sql_variant is 3750.
    @Description NVARCHAR(3750)
AS
BEGIN
    SET NOCOUNT ON;

    IF OBJECT_ID(@Table) IS NULL
    BEGIN
        RAISERROR('usp_Decco_SetDescription: object %s does not exist.', 16, 1, @Table);
        RETURN;
    END

    DECLARE @exists BIT = 0;

    IF @Column IS NULL
        SELECT @exists = 1
          FROM sys.extended_properties
         WHERE class = 1 AND major_id = OBJECT_ID(@Table) AND minor_id = 0
           AND name = N'MS_Description';
    ELSE
        SELECT @exists = 1
          FROM sys.extended_properties ep
          JOIN sys.columns c ON c.object_id = ep.major_id AND c.column_id = ep.minor_id
         WHERE ep.class = 1 AND ep.major_id = OBJECT_ID(@Table)
           AND c.name = @Column AND ep.name = N'MS_Description';

    IF @exists = 1
    BEGIN
        IF @Column IS NULL
            EXEC sp_updateextendedproperty N'MS_Description', @Description,
                 N'SCHEMA', N'dbo', N'TABLE', @Table;
        ELSE
            EXEC sp_updateextendedproperty N'MS_Description', @Description,
                 N'SCHEMA', N'dbo', N'TABLE', @Table, N'COLUMN', @Column;
    END
    ELSE
    BEGIN
        IF @Column IS NULL
            EXEC sp_addextendedproperty N'MS_Description', @Description,
                 N'SCHEMA', N'dbo', N'TABLE', @Table;
        ELSE
            EXEC sp_addextendedproperty N'MS_Description', @Description,
                 N'SCHEMA', N'dbo', N'TABLE', @Table, N'COLUMN', @Column;
    END
END
GO
