-- =============================================================================
-- TABLE descriptions — the 24 DeccoDB tables (21 from the baseline − Laboratorio + 4 from 0002/0003).
-- Lore vocabulary anchored in LORE-DECCO-BRUTO.md (workspace root).
-- Run-always, idempotent through usp_Decco_SetDescription.
-- =============================================================================

-- ── Catalogs (read-only, IdToCode/CodeToId targets) ─────────────────────────

EXEC dbo.usp_Decco_SetDescription 'Cat_ObjectClass', NULL,
 N'CATALOG. Containment class of the anomaly in the Brazilian system (PACATO, YAGUARA, ABAPORU, UKAR), with the ACS/SCP vocabulary equivalent in AcsClass. Defines the minimum clearance to see the anomaly and the UI severity color.';

EXEC dbo.usp_Decco_SetDescription 'Cat_FundamentalForce', NULL,
 N'CATALOG. The fictional fundamental forces behind anomalous phenomena: Kappa (informational coherence field) and Lambda (conscious non-baryonic substrate). It is the root of the ontological tree — every layer derives from a force.';

EXEC dbo.usp_Decco_SetDescription 'Cat_OntologicalLayer', NULL,
 N'CATALOG. The plane the anomaly operates on: THETA (anomalous physics, most cases), PSI (narrative/informational), PHI (consciousness/digital), OMEGA (non-baryonic substrate). Each layer belongs to a fundamental force.';

EXEC dbo.usp_Decco_SetDescription 'Cat_MatterType', NULL,
 N'CATALOG. What the anomaly is made of: Bariônica Anômala, Mista, Não-Bariônica or Indefinido. The IsSuppressorResistant flag marks matter immune to Theta suppression technology.';

EXEC dbo.usp_Decco_SetDescription 'Cat_InteractionMechanism', NULL,
 N'CATALOG. HOW the anomaly acts on reality, in the LAYER-LETTER format (Active, Passive, Conditional). Each anomaly has a primary mechanism and, optionally, a secondary one — which can only be a mechanism flagged as a sub-nature.';

EXEC dbo.usp_Decco_SetDescription 'Cat_SpecificManifestation', NULL,
 N'CATALOG. Observable, cataloged effects (shapeshifting, telekinesis, space-time distortion...). Linked to skills through AnomalySkill_Manifestation, with an intensity per link.';

EXEC dbo.usp_Decco_SetDescription 'Cat_ApparentCognition', NULL,
 N'CATALOG of the Brazilian System (OA Protocol). Degree of cognition measured on the anomaly: SE (Sentient), SA (Sapient), IN (Inanimate), AA (Anomalous Automaton). Part of the OA identifier, generated by the application.';

EXEC dbo.usp_Decco_SetDescription 'Cat_DangerLevel', NULL,
 N'CATALOG of the Brazilian System (OA Protocol). A 9-level scale, from Minimum to Maximum. From level 8 on there is a risk of breaking the Veil/Esquadria and the containment protocol becomes special.';

EXEC dbo.usp_Decco_SetDescription 'Cat_FacilityType', NULL,
 N'CATALOG. Facility types: SITIO, LABORATORIO, AREA_CONTENCAO, POSTO_AVANCADO. The AllowsChildren flag defines the hierarchy — a type that allows children is a root, the others live inside it.';

EXEC dbo.usp_Decco_SetDescription 'Cat_OperationType', NULL,
 N'CATALOG. Operation types: INVESTIGACAO, PESQUISA, SUPRESSAO. Defines whether the type requires a cataloged anomaly as its target (RequiresAnomaly) and the suggested minimum clearance for the operation.';

-- ── Main aggregate ──────────────────────────────────────────────────────────

EXEC dbo.usp_Decco_SetDescription 'Anomaly', NULL,
 N'ROOT ENTITY. Each row is a record of the DeCCO anomaly catalog. It gathers the ontological classification (class, layer, matter, mechanisms), the Brazilian classification (cognition, dangerousness), the measurable Theta markers and the operational state. Id starts at 1000; the public identity is ScpCode.';

-- ── 1:N instances — how the same anomaly manifests ──────────────────────────

EXEC dbo.usp_Decco_SetDescription 'LivingEntity', NULL,
 N'1:N INSTANCE of Anomaly. The manifestation of the anomaly as a living being: species, biology, origin of power, intelligence level. Deleted in cascade with the parent anomaly.';

EXEC dbo.usp_Decco_SetDescription 'Artifact', NULL,
 N'1:N INSTANCE of Anomaly. The manifestation as an object: material, origin, spin property and usage (the ritual or procedure that triggers the effect). Deleted in cascade.';

EXEC dbo.usp_Decco_SetDescription 'Location', NULL,
 N'1:N INSTANCE of Anomaly. WHERE the anomaly manifests in the world — with geographic coordinates, effect radius and ambient IEIA-D reading. NOT to be confused with the containment site: this is where the phenomenon happens, not where it is kept.';

EXEC dbo.usp_Decco_SetDescription 'AnomalyEvent', NULL,
 N'1:N INSTANCE of Anomaly. The manifestation as an occurrence in time: window, periodicity, affected zone and trigger preconditions.';

-- ── Configuration / back office ─────────────────────────────────────────────

EXEC dbo.usp_Decco_SetDescription 'Facility', NULL,
 N'CONFIGURATION / SCOPE. A physical DeCCO place: site, laboratory, containment area or forward post (Cat_FacilityType). Two-level hierarchy — site at the root, the other types as children (TR_Facility_ValidateHierarchy). It is the PERMISSION BOUNDARY of the system: the user gets a list of facilities (a relation that lives in DeccoAuthDB) and the scoped work (Operation) is filtered by it. Absorbed the former Laboratorio table (migrations 0002/0004).';

EXEC dbo.usp_Decco_SetDescription 'Operation', NULL,
 N'SCOPED WORK. Investigation, research or suppression (Cat_OperationType) conducted INSIDE a facility — FacilityId is mandatory from creation. Unlike Anomaly, which is a global catalog, an operation belongs to a place, so it is the first entity whose access and cache are sliced by facility (keys decco:inst:{codigo}:operacao:*).';

EXEC dbo.usp_Decco_SetDescription 'ContainmentProtocol', NULL,
 N'CONFIGURATION. Versioned containment procedure: steps, required resources, urgency level and the object classes it applies to. Linked to anomalies through Protocol_AppliedTo.';

EXEC dbo.usp_Decco_SetDescription 'Protocol_AppliedTo', NULL,
 N'N:N RELATIONSHIP between ContainmentProtocol and Anomaly, with a validity window (start/end) and status. Answers: which protocols are active on this anomaly, and since when.';

EXEC dbo.usp_Decco_SetDescription 'AnomalyNotification', NULL,
 N'FIELD INPUT. Report of a phenomenon not yet cataloged, with location, priority and reporter. AnomalyId is null until the investigation concludes — it is the entry point of the funnel that ends in a catalog record.';

-- ── Skills and deviations ───────────────────────────────────────────────────

EXEC dbo.usp_Decco_SetDescription 'AnomalySkill', NULL,
 N'Named capability of an anomaly (what it can do), with its own mechanisms, level and activation cost. An anomaly can have several skills; the name is unique per anomaly.';

EXEC dbo.usp_Decco_SetDescription 'Instance_DeviantSkill', NULL,
 N'DEVIATION. Records that a specific INSTANCE (entity, artifact, location or event) exercises a skill differently from the parent anomaly. POLYMORPHIC reference: InstanceType + InstanceId, with no real FK — integrity belongs to the application.';

EXEC dbo.usp_Decco_SetDescription 'AnomalySkill_Manifestation', NULL,
 N'N:N RELATIONSHIP between AnomalySkill and Cat_SpecificManifestation, qualified by intensity. Translates an abstract skill into the observable effects it produces.';

EXEC dbo.usp_Decco_SetDescription 'Incident', NULL,
 N'HISTORY. Recorded occurrence involving an anomaly: type, report, security level, casualties and material damage. The IsSigmaEvent flag marks incidents of exceptional severity, counted in vw_SigmaReport.';
GO
