-- =============================================================================
-- Generates docs/DATA-DICTIONARY.md from the DATABASE ITSELF.
--
-- Why generated instead of hand-written: a manually maintained dictionary goes stale
-- on the first migration nobody remembered to reflect. Here the source of truth is
-- the extended properties applied by programmability/descriptions/ — the markdown is
-- just a projection.
--
-- Usage:
--   sqlcmd -S "(localdb)\MSSQLLocalDB" -d DeccoDB -i docs/generate-data-dictionary.sql ^
--          -o docs/DATA-DICTIONARY.md -h -1 -W -f 65001
-- =============================================================================
SET NOCOUNT ON;

PRINT '# Data Dictionary — DeccoDB';
PRINT '';
PRINT '> Generated by `docs/generate-data-dictionary.sql`. **Do not edit by hand** — change the descriptions in';
PRINT '> `programmability/descriptions/` and run the runner.';
PRINT '';

DECLARE @table SYSNAME, @description NVARCHAR(MAX);
DECLARE tableCursor CURSOR FAST_FORWARD FOR
    SELECT t.name,
           CAST(ep.value AS NVARCHAR(MAX))
      FROM sys.tables t
      LEFT JOIN sys.extended_properties ep
             ON ep.class = 1 AND ep.major_id = t.object_id
            AND ep.minor_id = 0 AND ep.name = N'MS_Description'
     WHERE t.name <> 'SchemaVersions'
     ORDER BY t.name;

OPEN tableCursor;
FETCH NEXT FROM tableCursor INTO @table, @description;
WHILE @@FETCH_STATUS = 0
BEGIN
    PRINT '## ' + @table;
    PRINT '';
    IF @description IS NOT NULL BEGIN PRINT @description; PRINT ''; END
    PRINT '| Column | Type | Nullable | Description |';
    PRINT '|---|---|---|---|';

    DECLARE @line NVARCHAR(MAX);
    DECLARE columnCursor CURSOR FAST_FORWARD FOR
        SELECT '| `' + c.name + '` | '
             + ty.name
             + CASE WHEN ty.name IN ('varchar','nvarchar','char','nchar')
                    THEN '(' + CASE WHEN c.max_length = -1 THEN 'MAX'
                                    ELSE CAST(c.max_length / CASE WHEN ty.name LIKE 'n%' THEN 2 ELSE 1 END AS VARCHAR(10)) END + ')'
                    WHEN ty.name = 'decimal'
                    THEN '(' + CAST(c.precision AS VARCHAR(10)) + ',' + CAST(c.scale AS VARCHAR(10)) + ')'
                    ELSE '' END
             + ' | ' + CASE WHEN c.is_nullable = 1 THEN 'yes' ELSE 'no' END
             + ' | ' + ISNULL(REPLACE(CAST(ep.value AS NVARCHAR(MAX)), '|', '\|'), '') + ' |'
          FROM sys.columns c
          JOIN sys.types ty ON ty.user_type_id = c.user_type_id
          LEFT JOIN sys.extended_properties ep
                 ON ep.class = 1 AND ep.major_id = c.object_id
                AND ep.minor_id = c.column_id AND ep.name = N'MS_Description'
         WHERE c.object_id = OBJECT_ID(@table)
         ORDER BY c.column_id;

    OPEN columnCursor;
    FETCH NEXT FROM columnCursor INTO @line;
    WHILE @@FETCH_STATUS = 0 BEGIN PRINT @line; FETCH NEXT FROM columnCursor INTO @line; END
    CLOSE columnCursor; DEALLOCATE columnCursor;

    PRINT '';
    FETCH NEXT FROM tableCursor INTO @table, @description;
END
CLOSE tableCursor; DEALLOCATE tableCursor;
